version: "3.8"

services:
        consumer:
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                ports:
                        - "80:80"
